---
- hosts: all
  remote_user: root
  gather_facts: false
  tasks: 
    - name: Update
      raw: apt -y --allow-unauthenticated update || true

    - name: Ensure python is available
      raw: test -e /usr/bin/python || apt install -y --allow-unauthenticated python-minimal

    - name: Ensure python-apt is available
      raw: test -d /usr/share/python-apt || apt install -y --allow-unauthenticated python-apt

    - name: Upgrade
      raw: apt -y --allow-unauthenticated upgrade

#    - name: Install repository KEY
#      apt_key:
#        id: C6B2AC7FBEB649F1
#        keyserver: pgp.mit.edu
#
    - name: Autoclean
      apt: 
        update_cache: yes
        autoclean: yes

- import_playbook: network.yml
- import_playbook: subutai.yml
